### ISSUE TITLE
Browser tab caption not displayed

### ISSUE THREAD

**Issue by muratmat** [PipedreamHQ/roadmap#141]
Browser tab (tested on Chrome 64bit Windows) does not display workflow name if the workflow has been just opened from the global list. A tab refresh (F5) fixes the bug (i.e. the tab shows the workflow name). By clicking 'Deploy' button, the bug raises again (i.e. the browser tab does not display the workflow name, but just 'Pipedream' caption).

![pipedrem_tab_bug](https://user-images.githubusercontent.com/507813/69712975-033b9800-1104-11ea-9ba0-82232297d414.png)

**Comment by dylburger** [comment]
@muratmat thanks for raising this. This should be fixed now (workflow name gets set correctly on navigation from the dashboard, and gets set on Save / Deploy).

Let me know if you see any other related issues.

**Comment by muratmat** [comment]
Hi Dylan,

The issue seems to be mitigated now, but not solved ;)
In the detail, the workflow name disappears from browser tab as soon as 
an event item (from the column of received events) is clicked.

How can we proceed? I have to open another issue on Github or you can 
handle the flow internally?
Many thanks for your great work.

Best Regards,
    Matteo.

------ Original Message ------

**Comment by dylburger** [comment]
Hi Matteo, you're correct and we're implementing a fix. I re-opened the issue and will let you know when it's done.

**Comment by tjk** [comment]
This should be working now -- thanks for raising it @muratmat and please let us know if something is still wonky!
